name: Publish to gh-pages

on:
  pull_request:
    branches:
      - master

jobs:
  publish:
    name: Build and Publish to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: nodeModules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn dapp:build
        env:
          REACT_APP_DEFAULT_BRIDGE_DIRECTION: eth-bsc
          REACT_APP_ENABLED_BRIDGES: 'eth-xdai bsc-xdai eth-bsc'
          REACT_APP_INFURA_ID: ''
          REACT_APP_GAS_PRICE_FALLBACK_GWEI: 50
          REACT_APP_GAS_PRICE_SUPPLIER_URL: https://gasprice.poa.network/
          REACT_APP_GAS_PRICE_SPEED_TYPE: fast
          REACT_APP_GAS_PRICE_UPDATE_INTERVAL: 60000
          REACT_APP_ETH_PRICE_API_URL: 'https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=USD'
          REACT_APP_ETH_PRICE_UPDATE_INTERVAL: 60000
          REACT_APP_TITLE: MaskBridge - %c
          REACT_APP_DESCRIPTION: 'MaskBirdge UI is a web application interacting with MaskSwapAgent.'
          REACT_APP_UI_STATUS_UPDATE_INTERVAL: 5000
          REACT_APP_DEBUG_LOGS: false
          REACT_APP_GRAPH_HEALTH_UPDATE_INTERVAL: 60000
          REACT_APP_GRAPH_HEALTH_THRESHOLD_BLOCKS: 10
          REACT_APP_XDAI_RPC_URL: https://rpc.xdaichain.com https://dai.poa.network
          REACT_APP_SOKOL_RPC_URL: https://sokol.poa.network
          REACT_APP_MAINNET_RPC_URL: https://mainnet-nethermind.blockscout.com/
          REACT_APP_KOVAN_RPC_URL: https://kovan.poa.network/
          REACT_APP_BSC_RPC_URL: https://bsc-dataseed.binance.org https://bsc-dataseed1.defibit.io/
